# /kubernetes/ingress.yaml
# Manages external access to the WebUI using the AWS Application Load Balancer.

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: open-webui-ingress
  annotations:
    # This annotation is no longer needed and should be removed.
    # kubernetes.io/ingress.class: alb 
    
    # Creates an internet-facing ALB.
    alb.ingress.kubernetes.io/scheme: internet-facing
    # Routes traffic directly to pods for better performance.
    alb.ingress.kubernetes.io/target-type: ip
spec:
  # This new line explicitly tells the Ingress to use the 'alb' IngressClass.
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: open-webui-service
                port:
                  number: 8080