# /kubernetes/webui-deployment.yaml
# Deploys the stateless Open WebUI frontend.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:main
          ports:
            - containerPort: 8080
          env:
            # Points the WebUI to the internal Kubernetes service for Ollama.
            - name: OLLAMA_BASE_URL
              value: http://ollama-service:11434